import Navbar from '@/components/modules/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Bloom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Navbar />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
